### ISSUE TITLE
demo(unitizer) fails with

### ISSUE THREAD

**Issue by richierocks** [brodieG/unitizer#198]
I just tried `demo(unitizer)` again, this time under R-3.3.2 and macOS Sierra. It failed at this point:

```
> unitize(.unitizer.test.file)

+------------------------------------------------------------------------------------------+
| unitizer for: unitizer/fastlm1.R                                                         |
+------------------------------------------------------------------------------------------+

             Pass Fail  New
 <untitled>     -    -    4
...........................
                -    -    4

- New --------------------------------------------------------------------------------------

| The 4 tests in this section are new. Add tests to store ([Y]es, [N]o, [P]rev, [B]rowse, 
| [R]erun, [Q]uit, [H]elp)?

# Assignments and calls to `library` are not considered tests by
# `unitizer` so you will not need to review them

> library(utzflm)
Error: is.open_con(hist.con) is not TRUE
In addition: Warning message:
In history_capt(history) : subscript out of bounds
Error in search_path_update(to@search.path, .self) : 
  Logic Error: path reorder failed; contact maintainer.
| Failed restoring global settings to original state; you may want
| to restart your R session to ensure all global settings are in a
| reasonable state.

| Unexpectedly exited before storing unitizer; tests were not saved or changed.
```

**Comment by brodieG** [comment]
I just tried again w/ 3.3.2 under Sierra, 3.3.1 in windows/Rstudio and 3.2 in Linux and they all worked, so 
this is a bit frustrating.  Do you mind trying:

* start new clean R session
* run `sessionInfo()`
* run `library(unitizer); demo(unitizer)`

You shouldn't have to go through the above, but it will help me figure if there is some weird interaction going on with other packages.  Thanks for being willing to give this another shot.

One problem with the demo is that because it is interactive I don't feed it through the travis tests, etc., but pretty much everything used by the demo is tested.

**Comment by brodieG** [comment]
Also, are you running this in a normal terminal?  I had a similar problem a long time ago with non-interactive sessions that don't use history files.  Can you also try running `history()` and see if it shows the history before you do the above?

**Comment by brodieG** [comment]
I pushed a new version that allows you turn off history for the time being so hopefully you can run the demo.
```
devtools::install_github('brodieG/unitizer@issue198')
library(unitizer)
options(unitizer.history.file=NULL)
demo(unitizer)
```

**Comment by richierocks** [comment]
I tried 

```{r}
devtools::install_github('brodieG/unitizer@issue198')
library(unitizer)
options(unitizer.history.file=NULL)
demo(unitizer)
```

in both R GUI and RStudio and it worked fine.

**Comment by richierocks** [comment]
Actually it also seems fine when I omit the `options(unitizer.history.file=NULL)` line.

**Comment by brodieG** [comment]
Hmm.  I'm guessing there was some weird interaction with the state of your session then.  Those are lovely to debug.  Do you happen to remember if you were in an old session or fresh when you ran into the problem above?  I'll leave this issue open for now.
