### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by hubabe** [brodieG/unitizer#271]
I am working with R version 4.03 on ubuntu 20.04 64 bits. When trying to update unitizer I get the following error:
Installing package into '/home/hugo/R/x86_64-pc-linux-gnu-library/4.0'
(as ‘lib’ is unspecified)
testing the url 'https://cloud.r-project.org/src/contrib/unitizer_1.4.12.tar.gz'
Content type 'application / x-gzip' length 693207 bytes (676 KB)
================================================
downloaded 676 KB

* installing * source * package ‘unitizer’ ...
** package ‘unitizer’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Error in completeSubclasses (classDef2, class1, obj, where):
  attempt to obtain a "subclasses" slot of an object of a basic class ("NULL") without slots
Error: package or namespace load failed for 'dbplyr':
 .onLoad failed in loadNamespace () for 'dbplyr', details:
  call: setClass (cl, contains = c (prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
Error in .requirePackage (package):
  unable to find required package ‘dbplyr’
Calls: <Anonymous> ... .recacheSubclasses -> getClassDef -> .requirePackage
Execution interrupted
ERROR: lazy loading failed for package ‘unitizer’
* removing '/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer'
* restoring previous ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer’
Warning in install.packages:
  installation of package ‘unitizer’ had non-zero exit status

The downloaded source packages are in
‘/ Tmp / RtmpZIPY1P / downloaded_packages’

update was tested with dbplyr and without dbplyr

**Comment by brodieG** [comment]
Thanks for reporting.  Will you please provide the exact set of commands that led to this failure?  Did you just run:

```
install.packages('unitizer')
```

Will you also run:

```
sessionInfo()
```

Right after the failure and report the results?

If you can do all this in a fresh R session it would be best.

**Comment by brodieG** [comment]
Since I have not heard back from you I am going to close this issue.  If you wish feel free to re-open it again with the requested information.
